confirmOnQuit: true
gui:
  showIcons: true
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - black
    selectedLineBgColor:
      - blue
    defaultFgColor:
      - black
