#!/run/current-system/sw/bin/bash

URL=$1
TYPE=$2

echo "$URL" "$TYPE"

case "$TYPE" in
  article | link)
  # Don't open newsboat in a nix-shell
  qutebrowser --target tab "$URL"
  ;; 

  image)
  # cd "$(mktemp -d)" || exit
  # wget "$URL"
  echo "Loading..."
  kitty icat "$URL"
  read -p "Press Enter to return"
  ;;
esac

      
